---
#
# Install logstash
#
- name: take off swap file
  shell: "sudo swapoff -a"

- name: rpm -ql logstash
  shell: rpm -ql logstash | grep -v not | wc -l 
  register: ls_installed
- debug:
    var: ls_installed

- name: ps logstash
  shell: ps -ef | grep logstash | grep -v grep | wc -l
  register: ls_state

- debug:
    var: ls_state

# - name: stop logstash
#   # shell: "systemctl stop logstash"

#   systemd:
#     name: logstash
#     state: stopped
#   when: ls_state.stdout != "0" 

- name: Uninstall logstash
  yum:
    name: logstash
    state: absent
  when: ls_installed.stdout != "0"     

- name: remove all logstash file
  shell: "find / -name '*logstash*' | xargs rm -rf"
  when: ls_installed.stdout != "0" 


  
- name: Install logstash
  yum:
    name: logstash
    state: present


- name: create certs path
  file:
    path: "{{ certpath }}"
    group: root
    owner: root
    mode: 0755
    state: directory


- name: create jvm.options with template
  template:
    src: jvm.options.j2
    dest: "{{ packagepath }}/jvm.options"
    force: yes
    mode: 0644


- name: create logstash.yml with template
  template:
    src: logstash.yml.j2
    dest: "{{ packagepath }}/logstash.yml"
    owner: root
    group: root
    mode: 0644
    force: yes


- name: cerate logstash.conf with template
  template:
    src: logstash.conf.j2
    dest: "{{ packagepath }}/conf.d/logstash.conf"
    owner: root
    group: root
    mode: 0644
    force: yes


- name: copy ca files
  copy:
    src: "{{ ca_file }}"
    dest: "{{ certpath }}/{{ ca_file }}"
    owner: root
    group: root
    mode: 0600


- name: copy cert files
  copy:
    src: "{{ cert_file }}"
    dest: "{{ certpath }}/{{ cert_file }}"
    owner: root
    group: root
    mode: 0644


- name: enable logstash
  systemd:
    name: logstash
    enabled: yes
    daemon_reload: yes


- name: started logstash
  # shell: "systemctl start logstash"
  systemd:
    name: logstash
    state: started

