---
#
# Install logstash
#
- name: take off swap file
  shell: "sudo swapoff -a"

- name: stop logstash
  shell: "systemctl stop logstash"

#   systemd:
#     name: logstash
#     state: stopped

- name: Uninstall ogstash
  yum:
    name: logstash
    state: absent

- name: remove all ogstash file
  shell: "find / -name '*logstash*' | xargs rm -rf"


  
- name: Install logstash
  yum:
    name: logstash
    state: present

- name: create certs path
  file:
    path: "{{ certpath }}"
    group: root
    owner: root
    mode: 0755
    state: directory

- name: create jvm.options with template
  template:
    src: jvm.options.j2
    dest: "{{ packagepath }}/jvm.options"
    force: yes
    mode: 0644

- name: create logstash.yml with template
  template:
    src: logstash.yml.j2
    dest: "{{ packagepath }}/logstash.yml"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: cerate logstash.conf with template
  template:
    src: logstash.conf.j2
    dest: "{{ packagepath }}/conf.d/logstash.conf"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: copy ca files
  copy:
    src: "{{ ca_file }}"
    dest: "{{ certpath }}/{{ ca_file }}"
    owner: root
    group: root
    mode: 0600
  
- name: copy cert files
  copy:
    src: "{{ cert_file }}"
    dest: "{{ certpath }}/{{ cert_file }}"
    owner: root
    group: root
    mode: 0644

- name: enable logstash
  systemd:
    name: logstash
    enabled: yes
    daemon_reload: yes

- name: started logstash
  # shell: "systemctl start logstash"
  systemd:
    name: logstash
    state: started
    

