---
#
# Install logstash
#
- name: take off swap file
  shell: "sudo swapoff -a"

- name: rpm -ql logstash
  shell: rpm -ql logstash | grep -v not | wc -l 
  register: ls_installed
- debug:
    var: ls_installed

- name: ps logstash
  shell: ps -ef | grep logstash | grep -v grep | wc -l
  register: ls_state

- debug:
    var: ls_state

# - name: stop logstash
#   # shell: "systemctl stop logstash"

#   systemd:
#     name: logstash
#     state: stopped
#   when: ls_state.stdout != "0" 

- name: Uninstall logstash
  yum:
    name: logstash
    state: absent
  when: ls_installed.stdout != "0"     

- name: remove all logstash file
  shell: "find / -name '*logstash*' | xargs rm -rf"
  when: ls_installed.stdout != "0" 

- name: set elk6 repo
  yum_repository:
    name: elasticstack-6.x
    description: Elasticsearch repository for 6.x packages
    baseurl: https://mirrors.tuna.tsinghua.edu.cn/elasticstack/yum/elastic-6.x/
    enabled: yes
    gpgcheck: 0
    file: elk
  when: elk_version == "6.2.4"


- name: set elk7 repo
  yum_repository:
    name: elasticstack-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://mirrors.tuna.tsinghua.edu.cn/elasticstack/yum/elastic-7.x/
    enabled: yes
    gpgcheck: 0
    file: elk
  when: elk_version == "7.4.0"

- name: wait_for 9200
  wait_for:
    host: "{{ es_host }}"
    port: 9200
    delay: 10
  
- name: Install logstash
  yum:
    name: "logstash-{{ elk_version }}"
    state: present

- name: download xpack
  get_url:
    url: "{{ xpackurl }}"
    dest: /tmp
    force: no
    timeout: 30
  when: elk_version == "6.2.4" 

- name: install xpack
  shell: "/usr/share/logstash/bin/logstash-plugin install file:/tmp/x-pack-6.2.4.zip"
  when: elk_version == "6.2.4"  

- name: create certs path
  file:
    path: "{{ certpath }}"
    group: root
    owner: root
    mode: 0755
    state: directory


- name: create jvm.options with template
  template:
    src: jvm.options-{{ elk_version }}.j2
    dest: "{{ packagepath }}/jvm.options"
    force: yes
    mode: 0644


- name: create logstash.yml with template
  template:
    src: logstash-{{ elk_version }}.yml.j2
    dest: "{{ packagepath }}/logstash.yml"
    owner: root
    group: root
    mode: 0644
    force: yes

- 

- name: cerate logstash.conf with template
  template:
    src: logstash.conf.j2
    dest: "{{ packagepath }}/conf.d/logstash.conf"
    owner: root
    group: root
    mode: 0644
    force: yes


- name: copy ca files
  copy:
    src: "{{ ca_file }}"
    dest: "{{ certpath }}/{{ ca_file }}"
    owner: root
    group: root
    mode: 0600


- name: copy cert files
  copy:
    src: "{{ cert_file }}"
    dest: "{{ certpath }}/{{ cert_file }}"
    owner: root
    group: root
    mode: 0644


- name: enable logstash
  systemd:
    name: logstash
    enabled: yes
    daemon_reload: yes


- name: started logstash
  # shell: "systemctl start logstash"
  systemd:
    name: logstash
    state: started

- name: When this step is completed, the logstash system installation is completed 
  wait_for:
    host: "{{ ls_network_host }}"
    port: 5044
    delay: 10
