- hosts: es_servers
  tasks:
    - name: stop elasticsearch
      systemd:
        name: elasticsearch.service
        state: stopped

- hosts: ls_servers
  tasks:
    - name: stop logstash
      systemd:
        name: logstash.service
        state: stopped


- hosts: kibana_servers
  tasks:
    - name: stop kibana
      systemd:
        name: kibana.service
        state: stopped

- hosts: es_servers
  remote_user: root
  vars:
    - elk_version: 6.2.4
    - xpackurl: http://mirror.huolicard.com/Package/x-pack-6.2.4.zip
    - cluster_name: gxsk-dt-elk
    - discovery_seed_hosts: '["10.9.1.91", "10.9.1.92", "10.9.1.93"]'
    - initial_master_nodes: '["gxsk_es_01", "gxsk_es_02", "gxsk_es_03"]'
    - es_jvm_money: 11
  roles:
    - elasticsearch

- hosts: 10.9.1.91
  remote_user: root
  vars: 
    - elk_version: 6.2.4
    - es_host: 10.9.1.91
  roles:
    - esregist


- hosts: ls_servers
  remote_user: root
  vars:
    - elk_version: 6.2.4
    - xpackurl: http://mirror.huolicard.com/Package/x-pack-6.2.4.zip
    - elasticsearch_hosts: '["http://10.9.1.91:9200", "http://10.9.1.92:9200", "http://10.9.1.93:9200"]'
    - ls_jvm_money: 11
    - es_host: 10.9.1.91
  roles:
    - logstash 


- hosts: kibana_servers
  remote_user: root
  vars:
    - elk_version: 6.2.4
    - xpackurl: http://mirror.huolicard.com/Package/x-pack-6.2.4.zip
    - es_host: 10.9.1.92
    - elasticsearch_hosts: '["http://10.9.1.91:9200", "http://10.9.1.92:9200", "http://10.9.1.93:9200"]'
    - elasticache_url: "http://10.9.1.92:9200"
  roles:
    - kibana

