# - name: remove expect
#   yum:
#     name: expect
#     state: absent


- name: Install expect
  yum:
    name: expect
    state: present


- name: copy shell file
  copy:
    src: "{{ item }}"
    dest: /root/
    mode: 0755
  loop:
    - generatepass-{{ elk_version }}.sh
    - license.json


- name: create reg_license file with template
  template:
    src: reglicense.sh.j2
    dest: /root/reglicense.sh
    force: yes
    mode: 0755


- name: wait_for 9200
  wait_for:
    host: "{{ es_host }}"
    port: 9200
    delay: 10

- name: exec shell
  shell: "/root/generatepass-{{ elk_version }}.sh"
  
- name:  import license curl
  shell: "/root/reglicense.sh"


- name: delete file
  file:
    path: "/root/{{ item }}"
    state: absent
  loop:
    - generatepass-{{ elk_version }}.sh
    - license.json
    - reglicense.sh





